# Generated by Django 4.2.3 on 2023-07-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headphones', '0002_studentform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentform',
            new_name='Student',
        ),
    ]
