# Generated by Django 4.2.3 on 2023-07-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headphones', '0003_rename_studentform_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptopname', models.CharField(max_length=50)),
                ('laptopmodel', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('warranty', models.CharField(max_length=50)),
                ('memory', models.CharField(choices=[('1', '4 GB'), ('2', '8 GB'), ('3', '16 GB')], default='1', max_length=4)),
            ],
        ),
    ]
